### ISSUE TITLE
Clickable requires plugin -- Namelayer gui breaks it

### ISSUE THREAD

**Issue by ProgrammerDan** [Civcraft/CivModCore#16]
```
[03:07:49 ERROR]: Could not pass event InventoryClickEvent to NameLayer v2.8.03
org.bukkit.event.EventException
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:310) ~[spigot-1.10.jar:git-Spigot-6016ac7-d5ecbd0]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot-1.10.jar:git-Spigot-6016ac7-d5ecbd0]
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502) [spigot-1.10.jar:git-Spigot-6016ac7-d5ecbd0]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487) [spigot-1.10.jar:git-Spigot-6016ac7-d5ecbd0]
        at net.minecraft.server.v1_10_R1.PlayerConnection.a(PlayerConnection.java:1850) [spigot-1.10.jar:git-Spigot-6016ac7-d5ecbd0]
        at net.minecraft.server.v1_10_R1.PacketPlayInWindowClick.a(SourceFile:33) [spigot-1.10.jar:git-Spigot-6016ac7-d5ecbd0]
        at net.minecraft.server.v1_10_R1.PacketPlayInWindowClick.a(SourceFile:10) [spigot-1.10.jar:git-Spigot-6016ac7-d5ecbd0]
        at net.minecraft.server.v1_10_R1.PlayerConnectionUtils$1.run(SourceFile:13) [spigot-1.10.jar:git-Spigot-6016ac7-d5ecbd0]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471) [?:1.7.0_95]
        at java.util.concurrent.FutureTask.run(FutureTask.java:262) [?:1.7.0_95]
        at net.minecraft.server.v1_10_R1.SystemUtils.a(SourceFile:45) [spigot-1.10.jar:git-Spigot-6016ac7-d5ecbd0]
        at net.minecraft.server.v1_10_R1.MinecraftServer.D(MinecraftServer.java:733) [spigot-1.10.jar:git-Spigot-6016ac7-d5ecbd0]
        at net.minecraft.server.v1_10_R1.DedicatedServer.D(DedicatedServer.java:399) [spigot-1.10.jar:git-Spigot-6016ac7-d5ecbd0]
        at net.minecraft.server.v1_10_R1.MinecraftServer.C(MinecraftServer.java:672) [spigot-1.10.jar:git-Spigot-6016ac7-d5ecbd0]
        at net.minecraft.server.v1_10_R1.MinecraftServer.run(MinecraftServer.java:571) [spigot-1.10.jar:git-Spigot-6016ac7-d5ecbd0]
        at java.lang.Thread.run(Thread.java:745) [?:1.7.0_95]
Caused by: java.lang.IllegalArgumentException: Plugin cannot be null
        at org.apache.commons.lang.Validate.notNull(Validate.java:192) ~[spigot-1.10.jar:git-Spigot-6016ac7-d5ecbd0]
        at org.bukkit.craftbukkit.v1_10_R1.scheduler.CraftScheduler.validate(CraftScheduler.java:397) ~[spigot-1.10.jar:git-Spigot-6016ac7-d5ecbd0]
        at org.bukkit.craftbukkit.v1_10_R1.scheduler.CraftScheduler.runTaskTimer(CraftScheduler.java:123) ~[spigot-1.10.jar:git-Spigot-6016ac7-d5ecbd0
]
        at org.bukkit.craftbukkit.v1_10_R1.scheduler.CraftScheduler.scheduleSyncRepeatingTask(CraftScheduler.java:119) ~[spigot-1.10.jar:git-Spigot-60
16ac7-d5ecbd0]
        at org.bukkit.craftbukkit.v1_10_R1.scheduler.CraftScheduler.scheduleSyncDelayedTask(CraftScheduler.java:102) ~[spigot-1.10.jar:git-Spigot-6016
ac7-d5ecbd0]
        at vg.civcraft.mc.civmodcore.inventorygui.ClickableInventory.showInventory(ClickableInventory.java:170) ~[?:?]
        at vg.civcraft.mc.namelayer.gui.MainGroupGUI.showScreen(MainGroupGUI.java:163) ~[?:?]
        at vg.civcraft.mc.namelayer.gui.MainGroupGUI.<init>(MainGroupGUI.java:73) ~[?:?]
        at vg.civcraft.mc.namelayer.gui.GUIGroupOverview$5.clicked(GUIGroupOverview.java:213) ~[?:?]
        at vg.civcraft.mc.civmodcore.inventorygui.ClickableInventory.itemClick(ClickableInventory.java:140) ~[?:?]
        at vg.civcraft.mc.civmodcore.inventorygui.ClickableInventoryListener.inventoryClick(ClickableInventoryListener.java:28) ~[?:?]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.7.0_95]
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57) ~[?:1.7.0_95]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.7.0_95]
        at java.lang.reflect.Method.invoke(Method.java:606) ~[?:1.7.0_95]
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[spigot-1.10.jar:git-Spigot-6016ac7-d5ecbd0]
        ... 15 more

```

w.r.t. 1.10

**Comment by ProgrammerDan** [comment]
Impacts all plugins using clickableinventory. Joy!

**Comment by ProgrammerDan** [comment]
Ahhhh I see ... should be calling setPlugin. Will fix.

**Comment by ProgrammerDan** [comment]
So ... setting it static is going to cause all sorts of problems depending on level-of-overlap between plugins and CivModCore ... so ... yeah. Going to alter that and assume you're not using it.

**Comment by ProgrammerDan** [comment]
Referring to our offline conversion, this error is generated by the scheduling system, which requires a plugin owner for all tasks. I'm not entirely sure why, but most likely has to do with controlling cancellation and such.

I do recommend we simply require a plugin reference in the constructor as discussed. I can go ahead and do this later today most likely.

**Comment by Maxopoly** [comment]
Well, it only needs a plugin reference for the normal inventory, because they have some leftover code that's supposed to make "blinking" clickables work by updating them on a regular base. That never worked though, so we might as well remove it, not sure.
